### ISSUE TITLE
متن‌باز کردن وب‌سایت

### ISSUE THREAD

**Issue by machitgarha** [donateon/donateon-issuetracker#1]
<div dir="rtl">

سلام. در ابتدا لازمه که یه تشکر ویژه از همه‌ی توسعه‌دهندگان دونیتون و حمایت‌کنندگانش، به ویژه سازنده‌ی اصلی آقای صدیقی به عمل بیارم.

در این‌جا، من درخواستم این هست که اگر ممکنه، وب‌سایت به صورت آزاد و متن‌باز کدش در اختیار عموم قرار بگیره. این کار، مزیت اصلی‌اش این هست که دیگران هم به عنوان یک انجمن می‌تونن به توسعه‌ی وب‌سایت کمک بکنن. هم‌چنین، هر کسی می‌تونه نسخه‌ای برای خودش از نرم‌افزار رو روی سرور و دامنه‌ی شخصی‌سازی‌شده‌ای بسازه. و البته مزیت‌های مختلف دیگه‌ای که نرم‌افزارهای متن‌باز می‌تونن داشته باشن.

در صورت پذیرفته شدن، پیشنهاد من این هست که از پروانه‌ی [AGPLv3](https://www.gnu.org/licenses/agpl-3.0.html) استفاده بشه؛ چراکه نرم‌افزار آزاد خواهد موند و هر کس بخواد استفاده‌ای از کد روی شبکه (مثل ساخت یک وب‌سایت) بکنه، باید کد رو در اختیار بقیه هم قرار بده. اصولا به شخصه پروانه‌های کپی‌لفت رو بیش‌تر ترجیح می‌دم؛ اما خب این تنها یک پیشنهاده. 

</div>

**Comment by machitgarha** [comment]
<div dir="rtl">

و اگر درباره‌ی امنیت وب‌سایت نگرانی‌ای وجود داره، باید بگم که اتفاقا در این زمینه نرم‌افزارهای متن‌باز بهتر عمل کردن. ولی، اگر بخوام یه نمونه‌ی بزرگ بیارم از این، [نکست‌کلود](https://github.com/nextcloud) رو می‌گم که نه تنها متن‌باز هست همه‌ی خدماتش، بلکه از پروانه‌ی AGPLv3 هم استفاده می‌کنه.

</div>

**Comment by ariaieboy** [comment]
سلام  خدمت شما 
حقیقتا دونیتون تا الان دو تا ورژن بزرگ داشته ورژن اول را که من با مینی فریمورک دست ساز خودم بالا آوردم و توی ورژن دوم کوچ کردیم روی لاراول.
اما از اونجایی که کد ها خیلی کثیف هست و تست نویسی نشده  و من خودم دوستشون ندارم ترجیح میدم اپن سورس نکنم. 

شاید در آینده اینکار را انجام دادم ولی فعلا برنامه ای براش وجود نداره. 

برنامه دارم که یکسری از فانکشنالیتی ها و بخش هایی که میشه در قالب سرویس دربیاد را جداسازی کنم و  اپن سورس کنم ولی فعلا وقتش را ندارم.

3 تا 4 تا پروژه دارم که یکیش خیلی خیلی بزرگ هست در حال کار روی اونها هستم. 

اگر قسمت بشه شاید توی سال آینده حرکتی روی دونیتون زدیم.

**Comment by machitgarha** [comment]
<div dir="rtl">

@ariaieboy 

اگر کدها تمیز نیستن به اندازه‌ی کافی و تست‌نویسی نشدن، اگر با متن‌باز شدن‌اش موافقید، امکانش هست کد رو به اشتراک بگذارید تا بلکه احتمال این وجود داشته باشه که انجمن این تمیزکاری و این کارها رو انجام بده؟ این‌جوری هم هزینه‌ای براتون نداره و هم می‌تونید به کارتون برسید.

البته این اتفاق بدیهیه که قطعی نیست روی دادنش؛ اما به نظرم از هیچی بهتره... چراکه اگر این متن‌باز شدن بخواد پس از تمیزکاری یا هر چیز دیگه‌ای اتفاق بیفته، و این کار طول بکشه، توی همین زمان و بلکه کمتر، احتمال داره این کار رو دیگران روی کد انجام بدن.

البته متوجهم که چرا تمیزکاری رو می‌گید، اما می‌خوام بگم به سودش می‌ارزه. چون، تمیزکاری برای این خوب و مطلوبه که خوانایی رو برای بقیه فراهم کنه تا بقیه هم بتونن مشارکت کنن. اما، به نظرم، فرقی نداره که این کار رو چه کسی انجام بده و این‌که خیلی از افراد اصولا حتی به کد منبع نگاه (به هر منظوری) هم نخواهند کرد؛ حتی اون‌هایی که می‌خوان استفاده‌ی شخصی داشته باشن.

</div>
