### ISSUE TITLE
توسعه سایت متوقف شده؟

### ISSUE THREAD

**Issue by shahriaarrr** [donateon/donateon-issuetracker#2]
سلام وقتتون بخیر خسته نباشید
میخواستم بپرسم وبسایت دونیتون توسعش رها شده؟ چون دیدم تو صفحه حمایت مالیش هدف پرداخت زیرساخت های 1401 هست و ما الان در 1402 هستیم.
آیا توسعه و پشتیبانی این پلتفرم متوقف شده یا خیر؟
@ariaieboy

**Comment by ariaieboy** [comment]
سلام خدمت شما
خیلی وقت هست به جز رفع مشکلات جزیی و بحث maintenance بروزرسانی دیگه ای روی سایت اعمال نشده و عملا توسعه ای را نداشتیم.
اما بحث پشتیبانی ما همچنان ادامه داره و سایت بدون مشکل کار می‌کنه. در صورتیکه مشکلی گزارش بشه سعی میکنیم برطرف کنیم.

در مورد آینده دونیتون هم حداقل تا شش ماه آینده ما سرور داریم و بعد از اون هم اگر مشکلی پیش نیاد سعی میکنیم حتی بدون اسپانسر سایت را آنلاین نگهداریم تا دوستان بتونن استفاده کنند.

در مورد بحث توسعه هم برنامه هایی داریم ولی باید هم وقت مقتضی داشته باشیم هم اینکه منتظر یکسری تغییرات هستیم که بعد از اون کار روی آپدیت جدید سایت شروع کنیم.

اگر همه چیز طبق برنامه پیش بره احتمالا تا قبل از سال جدید یک بروزرسانی کامل روی دونیتون انجام بدیم.ولی قول نمیدیم.

**Comment by shahriaarrr** [comment]
خیلی هم عالیه انشاا... موفق باشید
